apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-django-4

spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app-2
  template:
    metadata:
      labels:
        app: django-app-2
    spec:
      containers:
      - name: django-container
        image: eric096/django-kubernetes:15
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet: 
            path: /teste-kubernetes
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 20
        envFrom:
        - secretRef:
            name: secret-django-db
        volumeMounts:
        - name: "volume-by-django"
          mountPath: "/my-data"
      volumes:
      - name: "volume-by-django"
        hostPath:
          path: "/var/lib/volume-django"
      