apiVersion: v1
kind: Service
metadata:
  name: service-postgres

spec:
  type: LoadBalancer
  selector:
    app: app-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 30000



